const Menuchartapi = [
    {
        id: 1,
        iconH: "fas fa-heart",
        iconeye: "fas fa-eye",
        iconretingf: "fas fa-star",
        iconretinghalf: "fas fa-star-half-alt",
        image: "../images/menu-1.jpg",
        title: "tasty food",
        subtitle: "",
        category: "",
        price: "$15.99",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
        btn: "add to cart"
        },
        {
            id: 2,
            iconH: "fas fa-heart",
            iconeye: "fas fa-eye",
            iconretingf: "fas fa-star",
            iconretinghalf: "fas fa-star-half-alt",
            image: "../images/menu-2.jpg",
            title: "tasty food",
            subtitle: "",
            category: "",
            price: "$15.99",
            description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
            btn: "add to cart"
            },
            {
                id: 3,
                iconH: "fas fa-heart",
                iconeye: "fas fa-eye",
                iconretingf: "fas fa-star",
                iconretinghalf: "fas fa-star-half-alt",
                image: "../images/menu-3.jpg",
                title: "tasty food",
                subtitle: "",
                category: "",
                price: "$15.99",
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                btn: "add to cart"
                },
                {
                    id: 4,
                    iconH: "fas fa-heart",
                    iconeye: "fas fa-eye",
                    iconretingf: "fas fa-star",
                    iconretinghalf: "fas fa-star-half-alt",
                    image: "../images/menu-4.jpg",
                    title: "tasty food",
                    subtitle: "",
                    category: "",
                    price: "$15.99",
                    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                    btn: "add to cart"
                    },
                    {
                        id: 5,
                        iconH: "fas fa-heart",
                        iconeye: "fas fa-eye",
                        iconretingf: "fas fa-star",
                        iconretinghalf: "fas fa-star-half-alt",
                        image: "../images/menu-5.jpg",
                        title: "tasty food",
                        subtitle: "",
                        category: "",
                        price: "$15.99",
                        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                        btn: "add to cart"
                        },
                        {
                            id: 6,
                            iconH: "fas fa-heart",
                            iconeye: "fas fa-eye",
                            iconretingf: "fas fa-star",
                            iconretinghalf: "fas fa-star-half-alt",
                            image: "../images/menu-6.jpg",
                            title: "tasty food",
                            subtitle: "",
                            category: "",
                            price: "$15.99",
                            description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                            btn: "add to cart"
                            },
                            {
                                id: 7,
                                iconH: "fas fa-heart",
                                iconeye: "fas fa-eye",
                                iconretingf: "fas fa-star",
                                iconretinghalf: "fas fa-star-half-alt",
                                image: "../images/menu-7.jpg",
                                title: "tasty food",
                                subtitle: "",
                                category: "",
                                price: "$15.99",
                                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                                btn: "add to cart"
                                },
                                {
                                    id: 8,
                                    iconH: "fas fa-heart",
                                    iconeye: "fas fa-eye",
                                    iconretingf: "fas fa-star",
                                    iconretinghalf: "fas fa-star-half-alt",
                                    image: "../images/menu-8.jpg",
                                    title: "tasty food",
                                    subtitle: "",
                                    category: "",
                                    price: "$15.99",
                                    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                                    btn: "add to cart"
                                    },
                                    {
                                        id: 9,
                                        iconH: "fas fa-heart",
                                        iconeye: "fas fa-eye",
                                        iconretingf: "fas fa-star",
                                        iconretinghalf: "fas fa-star-half-alt",
                                        image: "../images/menu-9.jpg",
                                        title: "tasty food",
                                        subtitle: "",
                                        category: "",
                                        price: "$15.99",
                                        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium." ,
                                        btn: "add to cart"
                                        },
                                        
]
export default Menuchartapi;